export const CHAT_CASE_ACTION_START = "CHAT_CASE_ACTION_START";
export const CHAT_CASE_ACTION_FINISH = "CHAT_CASE_ACTION_FINISH";
export const CHAT_CASE_ACTION_ERROR = "CHAT_CASE_ACTION_ERROR";
export const GET_CASE_REPLIES = "GET_CASE_REPLIES";
export const GET_CASE_DOCTOR = "GET_CASE_DOCTOR";
export const GET_CASE_PATIENT = "GET_CASE_PATIENT";

export type ChatCaseActionTypes = typeof CHAT_CASE_ACTION_START &
    typeof CHAT_CASE_ACTION_FINISH &
    typeof CHAT_CASE_ACTION_ERROR &
    typeof GET_CASE_REPLIES &
    typeof GET_CASE_PATIENT &
    typeof GET_CASE_DOCTOR;
