export const CHAT_CASE_ACTION_START = "CHAT_CASE_ACTION_START";
export const CHAT_CASE_ACTION_FINISH = "CHAT_CASE_ACTION_FINISH";
export const CHAT_CASE_ACTION_ERROR = "CHAT_CASE_ACTION_ERROR";
export const SET_CASE_REPLIES = "SET_CASE_REPLIES";
export const SET_CASE_DOCTOR = "SET_CASE_DOCTOR";
export const SET_CASE_PATIENT = "SET_CASE_PATIENT";

export type ChatCaseActionTypes = typeof CHAT_CASE_ACTION_START &
    typeof CHAT_CASE_ACTION_FINISH &
    typeof CHAT_CASE_ACTION_ERROR &
    typeof SET_CASE_REPLIES &
    typeof SET_CASE_PATIENT &
    typeof SET_CASE_DOCTOR;
