export const QUESTION_TEMPLATE_ACTION_START = "QUESTION_TEMPLATE_ACTION_START";
export const QUESTION_TEMPLATE_ACTION_FINISH = "QUESTION_TEMPLATE_ACTION_FINISH";
export const QUESTION_TEMPLATE_ACTION_ERROR = "QUESTION_TEMPLATE_ACTION_ERROR";
export const SET_SAVED_QUESTIONS = "SET_SAVED_QUESTIONS";
export const ADD_QUESTION_TO_TEMPLATE = "ADD_QUESTION_TO_TEMPLATE";
export const SEND_CASE_QUESTIONS = "SEND_CASE_QUESTIONS";

export type QuestionTemplateActionTypes = typeof QUESTION_TEMPLATE_ACTION_START &
    typeof QUESTION_TEMPLATE_ACTION_FINISH &
    typeof QUESTION_TEMPLATE_ACTION_ERROR &
    typeof SET_SAVED_QUESTIONS &
    typeof ADD_QUESTION_TO_TEMPLATE &
    typeof SEND_CASE_QUESTIONS;
