export const SET_PAYMENT_RECEIPTS = "SET_PAYMENT_RECEIPTS";
export const PAYMENT_RECEIPTS_LIST_ACTION_START = "PAYMENT_RECEIPTS_LIST_ACTION_START";
export const PAYMENT_RECEIPTS_LIST_ACTION_FINISH = "PAYMENT_RECEIPTS_LIST_ACTION_FINISH";
export const PAYMENT_RECEIPTS_LIST_ACTION_ERROR = "PAYMENT_RECEIPTS_LIST_ACTION_ERROR";
export const SORT_RECEIPTS_LIST = "SORT_RECEIPTS_LIST";
export const FILTER_RECEIPTS = "FILTER_RECEIPTS";
export const CLEAR_RECEIPT_LISTS = "CLEAR_RECEIPT_LISTS";

export type PaymentReceiptsListActionTypes = typeof SET_PAYMENT_RECEIPTS &
    typeof PAYMENT_RECEIPTS_LIST_ACTION_START &
    typeof PAYMENT_RECEIPTS_LIST_ACTION_FINISH &
    typeof PAYMENT_RECEIPTS_LIST_ACTION_ERROR &
    typeof SORT_RECEIPTS_LIST &
    typeof FILTER_RECEIPTS &
    typeof CLEAR_RECEIPT_LISTS;
