export const SET_MY_CASES = "SET_MY_CASES";
export const MY_CASES_LIST_ACTION_START = "MY_CASES_LIST_ACTION_START";
export const MY_CASES_LIST_ACTION_FINISH = "MY_CASES_LIST_ACTION_FINISH";
export const MY_CASES_LIST_ACTION_ERROR = "MY_CASES_LIST_ACTION_ERROR";
export const SORT_CASES_LIST = "SORT_CASES_LIST";
export const FILTER_CASES = "FILTER_CASES";
export const CLEAR_CASE_LISTS = "CLEAR_CASE_LISTS";
export const SET_PENDING_TRANSFERS = "SET_PENDING_TRANSFERS";
export const ADD_NEW_CASE_ACTION = "ADD_NEW_CASE_ACTION";
export const UPDATE_CASE_IN_MY_LIST_ACTION = "UPDATE_CASE_IN_MY_LIST_ACTION";

export type MyCasesListActionTypes = typeof SET_MY_CASES &
    typeof MY_CASES_LIST_ACTION_START &
    typeof MY_CASES_LIST_ACTION_FINISH &
    typeof MY_CASES_LIST_ACTION_ERROR &
    typeof SORT_CASES_LIST &
    typeof FILTER_CASES &
    typeof CLEAR_CASE_LISTS &
    typeof ADD_NEW_CASE_ACTION &
    typeof SET_PENDING_TRANSFERS &
    typeof UPDATE_CASE_IN_MY_LIST_ACTION;
