export const HISTORY_CASE_ACTION_START = "HISTORY_CASE_ACTION_START";
export const HISTORY_CASE_ACTION_FINISH = "HISTORY_CASE_ACTION_FINISH";
export const HISTORY_CASE_ACTION_ERROR = "HISTORY_CASE_ACTION_ERROR";
export const SET_HISTORY_CASE_REPLIES = "SET_HISTORY_CASE_REPLIES";

export type HistoryCaseActionTypes = typeof HISTORY_CASE_ACTION_START &
    typeof HISTORY_CASE_ACTION_FINISH &
    typeof HISTORY_CASE_ACTION_ERROR &
    typeof SET_HISTORY_CASE_REPLIES;
