export const TRANSFER_CASE_ACTION_START = "TRANSFER_CASE_ACTION_START";
export const TRANSFER_CASE_ACTION_FINISH = "TRANSFER_CASE_ACTION_FINISH";
export const TRANSFER_CASE_ACTION_ERROR = "TRANSFER_CASE_ACTION_ERROR";
export const GET_SPECIALITY_DOCTORS = "GET_SPECIALITY_DOCTORS";
export const TRANSFER_REQUEST_SUCCESSFUL = "TRANSFER_REQUEST_SUCCESSFUL";

export type TransferCaseActionTypes = typeof TRANSFER_CASE_ACTION_START &
    typeof TRANSFER_CASE_ACTION_FINISH &
    typeof TRANSFER_CASE_ACTION_ERROR &
    typeof GET_SPECIALITY_DOCTORS &
    typeof TRANSFER_REQUEST_SUCCESSFUL;
