export const GET_PRIMARY_SPECIALITIES = "GET_PRIMARY_SPECIALITIES";
export const GET_SECONDARY_SPECIALITIES = "GET_SECONDARY_SPECIALITIES";
export const GET_INITIAL_REQUIRED_QUESTIONS = "GET_INITIAL_REQUIRED_QUESTIONS";
export const GET_INITIAL_NOT_REQUIRED_QUESTIONS = "GET_INITIAL_NOT_REQUIRED_QUESTIONS";
export const GET_REQUIRED_QUESTIONS = "GET_REQUIRED_QUESTIONS";
export const GET_NOT_REQUIRED_QUESTIONS = "GET_NOT_REQUIRED_QUESTIONS";

export const NEW_CASE_ACTION_START = "NEW_CASE_ACTION_START";
export const NEW_CASE_ACTION_FINISH = "NEW_CASE_ACTION_FINISH";
export const NEW_CASE_ACTION_ERROR = "NEW_CASE_ACTION_ERROR";

export type NewCaseActionTypes = typeof GET_PRIMARY_SPECIALITIES &
    typeof GET_SECONDARY_SPECIALITIES &
    typeof GET_INITIAL_REQUIRED_QUESTIONS &
    typeof GET_INITIAL_NOT_REQUIRED_QUESTIONS &
    typeof GET_REQUIRED_QUESTIONS &
    typeof GET_NOT_REQUIRED_QUESTIONS &
    typeof NEW_CASE_ACTION_START &
    typeof NEW_CASE_ACTION_FINISH &
    typeof NEW_CASE_ACTION_ERROR;
