export const SET_PRIMARY_SPECIALITIES = "SET_PRIMARY_SPECIALITIES";
export const SET_SECONDARY_SPECIALITIES = "SET_SECONDARY_SPECIALITIES";
export const SET_INITIAL_REQUIRED_QUESTIONS = "SET_INITIAL_REQUIRED_QUESTIONS";
export const SET_INITIAL_NOT_REQUIRED_QUESTIONS = "SET_INITIAL_NOT_REQUIRED_QUESTIONS";
export const SET_REQUIRED_QUESTIONS = "SET_REQUIRED_QUESTIONS";
export const SET_NOT_REQUIRED_QUESTIONS = "SET_NOT_REQUIRED_QUESTIONS";

export const NEW_CASE_ACTION_START = "NEW_CASE_ACTION_START";
export const NEW_CASE_ACTION_FINISH = "NEW_CASE_ACTION_FINISH";
export const NEW_CASE_ACTION_ERROR = "NEW_CASE_ACTION_ERROR";

export const SET_NEW_TO_BE_PAID_CASE = "SET_NEW_TO_BE_PAID_CASE";
export const REMOVE_NEW_TO_BE_PAID_CASE = "REMOVE_NEW_TO_BE_PAID_CASE";

export type NewCaseActionTypes = typeof SET_PRIMARY_SPECIALITIES &
    typeof SET_SECONDARY_SPECIALITIES &
    typeof SET_INITIAL_REQUIRED_QUESTIONS &
    typeof SET_INITIAL_NOT_REQUIRED_QUESTIONS &
    typeof SET_REQUIRED_QUESTIONS &
    typeof SET_NOT_REQUIRED_QUESTIONS &
    typeof NEW_CASE_ACTION_START &
    typeof NEW_CASE_ACTION_FINISH &
    typeof NEW_CASE_ACTION_ERROR &
    typeof SET_NEW_TO_BE_PAID_CASE &
    typeof REMOVE_NEW_TO_BE_PAID_CASE;
